---
# tasks file for ansible-role-qemu_user_static

- name: "Include vars/{{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include tasks/install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: See if qemu_user_static has been started
  shell: "binmiscctl list"
  register: __qemu_user_static_service_binmiscctl_list
  changed_when: false

- name: Start qemu_user_static
  # XXX qemu_user_static does not have `status`
  service:
    name: "{{ qemu_user_static_service }}"
    state: started
  when:
    - "__qemu_user_static_service_binmiscctl_list.stdout | length == 0"
